apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: test
spec:
  organization: yoshi65
  secretsMountPath: "/tmp/secrets"
  module:
    source: "git::https://github.com/yoshi65/sharing-session.git//terraform-cloud-operator/test-module"
  outputs:
    - key: url
      moduleOutputName: this_sqs_queue_id
    - key: arn
      moduleOutputName: this_sqs_queue_arn
  variables:
    - key: name
      value: "test"
      sensitive: false
      environmentVariable: false
    - key: fifo_queue
      value: "true"
      sensitive: false
      environmentVariable: false
    - key: AWS_DEFAULT_REGION
      valueFrom:
        configMapKeyRef:
          name: aws-configuration
          key: region
      sensitive: false
      environmentVariable: true
    - key: AWS_ACCESS_KEY_ID
      sensitive: true
      environmentVariable: true
    - key: AWS_SECRET_ACCESS_KEY
      sensitive: true
      environmentVariable: true
